workflows:
  build-with-tag:
    name: Build Specific Flavor Based on Tag
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        FLUTTER_BUILD_TAG: $BUILD_TAG # Tag dari pipeline atau Git
    scripts:
      - name: Parse Build Tag
        script: |
          # Ambil bagian terakhir dari tag (contoh: "release")
          TAG_SUFFIX=$(echo "$FLUTTER_BUILD_TAG" | awk -F'-' '{print $NF}')
          if [[ "$TAG_SUFFIX" == "dev" ]]; then
            FLUTTER_BUILD_FLAVOR="dev"
          elif [[ "$TAG_SUFFIX" == "baisdev" ]]; then
            FLUTTER_BUILD_FLAVOR="baisdev"
          elif [[ "$TAG_SUFFIX" == "stag" ]]; then
            FLUTTER_BUILD_FLAVOR="stag"
          elif [[ "$TAG_SUFFIX" == "release" ]]; then
            FLUTTER_BUILD_FLAVOR="prod"
          else
            echo "Invalid tag suffix: $TAG_SUFFIX"
            exit 1
          fi
          echo "Building flavor: $FLUTTER_BUILD_FLAVOR"
      - name: Update version in pubspec.yaml
        script: |
          VERSION_NAME=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          BUILD_NUMBER=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f2)
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          sed -i.bak "s/^version:.*/version: $VERSION_NAME+$NEW_BUILD_NUMBER/" pubspec.yaml
          echo "Updated version to $VERSION_NAME+$NEW_BUILD_NUMBER"
      - name: Install dependencies
        script: |
          flutter packages get
      - name: Build APK with Parsed Flavor
        script: |
          flutter build apk --flavor $FLUTTER_BUILD_FLAVOR
      - name: Build iOS App (Optional)
        script: |
          flutter build ios --flavor $FLUTTER_BUILD_FLAVOR
    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/**/*.ipa
