name: bais_mobile
description: "BAIS Project Mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+4

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.5.0+1
  dropdown_search: ^5.0.2
  get: ^4.6.6
  http: ^1.2.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0
  geocoding: ^3.0.0
  flutter_svg: ^2.0.10+1
  flutter_onboarding_slider: ^1.0.11
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_analytics: ^11.1.0
  google_sign_in: ^6.2.1
  getwidget: ^4.0.0
  get_storage: ^2.1.1
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  location: ^7.0.1
  path: ^1.9.0
  permission_handler: ^11.3.1
  rubber: ^1.1.0
  shimmer: ^3.0.0
  sqflite: ^2.3.2
  syncfusion_flutter_datepicker: ^26.2.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.3.2
  flutter_gen_runner: ^5.1.0
  json_serializable: ^6.5.3
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/img_app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/icons/
    - assets/icons/navigation/
    - assets/images/svg/navigation/
    - assets/images/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 100
        - asset: assets/fonts/Rubik/Rubik-LightItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-MediumItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Rubik/Rubik-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-ExtraBoldItalic.ttf
          weight: 700
          style: italic
